version: "3"

services:
  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    build: .

    # args:
    # if you're building on an architecture other than amd64, make sure
    # to define a maximum ram for node. otherwise the build will fail.
    #   - NODE_OPTIONS="--max_old_space_size=1024"
    # default is .
    #   - PUBLIC_URL=/synapse-admin
    # You can use a fixed homeserver, so that the user can no longer
    # define it himself
    #   - REACT_APP_SERVER="https://matrix.example.com"
    ports:
      - "8080:80"
    restart: unless-stopped
