name: Create release tarball and attach to tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn build
      - run: |
          version=`git describe --dirty --tags || echo unknown`
          mkdir -p dist
          cp -r build synapse-admin-$version
          tar chvzf dist/synapse-admin-$version.tar.gz synapse-admin-$version
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
